package com.huawei.mybatis.bean;

public class Ltsprojectpo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ltsprojectpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ltsprojectpo.project_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ltsprojectpo.model_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private Long modelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ltsprojectpo.id
     *
     * @return the value of ltsprojectpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ltsprojectpo.id
     *
     * @param id the value for ltsprojectpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ltsprojectpo.project_name
     *
     * @return the value of ltsprojectpo.project_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ltsprojectpo.project_name
     *
     * @param projectName the value for ltsprojectpo.project_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ltsprojectpo.model_id
     *
     * @return the value of ltsprojectpo.model_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ltsprojectpo.model_id
     *
     * @param modelId the value for ltsprojectpo.model_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }
}