package com.huawei.mybatis.bean;

public class Tablepo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablepo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablepo.table_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private String tableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablepo.id
     *
     * @return the value of tablepo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablepo.id
     *
     * @param id the value for tablepo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablepo.table_name
     *
     * @return the value of tablepo.table_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablepo.table_name
     *
     * @param tableName the value for tablepo.table_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }
}