package com.huawei.mybatis.bean;

public class Tablecolumnpo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablecolumnpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablecolumnpo.table_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private Long tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablecolumnpo.column_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablecolumnpo.column_type
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    private String columnType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablecolumnpo.id
     *
     * @return the value of tablecolumnpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablecolumnpo.id
     *
     * @param id the value for tablecolumnpo.id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablecolumnpo.table_id
     *
     * @return the value of tablecolumnpo.table_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public Long getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablecolumnpo.table_id
     *
     * @param tableId the value for tablecolumnpo.table_id
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablecolumnpo.column_name
     *
     * @return the value of tablecolumnpo.column_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablecolumnpo.column_name
     *
     * @param columnName the value for tablecolumnpo.column_name
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablecolumnpo.column_type
     *
     * @return the value of tablecolumnpo.column_type
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablecolumnpo.column_type
     *
     * @param columnType the value for tablecolumnpo.column_type
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }
}