package com.huawei.mybatis.dao;

import com.huawei.mybatis.bean.Tablecolumnpo;
import com.huawei.mybatis.bean.TablecolumnpoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablecolumnpoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    long countByExample(TablecolumnpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int deleteByExample(TablecolumnpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int insert(Tablecolumnpo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int insertSelective(Tablecolumnpo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    List<Tablecolumnpo> selectByExample(TablecolumnpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    Tablecolumnpo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Tablecolumnpo record, @Param("example") TablecolumnpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Tablecolumnpo record, @Param("example") TablecolumnpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Tablecolumnpo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablecolumnpo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByPrimaryKey(Tablecolumnpo record);
}