package com.huawei.mybatis.dao;

import com.huawei.mybatis.bean.Tablepo;
import com.huawei.mybatis.bean.TablepoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablepoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    long countByExample(TablepoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int deleteByExample(TablepoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int insert(Tablepo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int insertSelective(Tablepo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    List<Tablepo> selectByExample(TablepoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    Tablepo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Tablepo record, @Param("example") TablepoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Tablepo record, @Param("example") TablepoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Tablepo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablepo
     *
     * @mbg.generated Fri Jun 15 02:03:06 GMT+08:00 2018
     */
    int updateByPrimaryKey(Tablepo record);
}